# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2023-06-13T00:15:58+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, SecretStr, confloat, conint, constr


class ActivityLimitExceeded(BaseModel):
    __root__: Any


class InvalidName(BaseModel):
    __root__: Any


class TooManyTags(BaseModel):
    __root__: Any


class InvalidArn(BaseModel):
    __root__: Any


class InvalidDefinition(BaseModel):
    __root__: Any


class InvalidLoggingConfiguration(BaseModel):
    __root__: Any


class InvalidTracingConfiguration(BaseModel):
    __root__: Any


class StateMachineAlreadyExists(BaseModel):
    __root__: Any


class StateMachineDeleting(BaseModel):
    __root__: Any


class StateMachineLimitExceeded(BaseModel):
    __root__: Any


class StateMachineTypeNotSupported(BaseModel):
    __root__: Any


class DeleteActivityOutput(BaseModel):
    pass


class DeleteStateMachineOutput(BaseModel):
    pass


class ValidationException(BaseModel):
    __root__: Any


class ActivityDoesNotExist(BaseModel):
    __root__: Any


class ExecutionDoesNotExist(BaseModel):
    __root__: Any


class ResourceNotFound(BaseModel):
    __root__: Any


class StateMachineDoesNotExist(BaseModel):
    __root__: Any


class ActivityWorkerLimitExceeded(BaseModel):
    __root__: Any


class InvalidToken(BaseModel):
    __root__: Any


class SendTaskFailureOutput(BaseModel):
    pass


class TaskDoesNotExist(BaseModel):
    __root__: Any


class TaskTimedOut(BaseModel):
    __root__: Any


class SendTaskHeartbeatOutput(BaseModel):
    pass


class SendTaskSuccessOutput(BaseModel):
    pass


class InvalidOutput(BaseModel):
    __root__: Any


class ExecutionLimitExceeded(BaseModel):
    __root__: Any


class ExecutionAlreadyExists(BaseModel):
    __root__: Any


class InvalidExecutionInput(BaseModel):
    __root__: Any


class TagResourceOutput(BaseModel):
    pass


class UntagResourceOutput(BaseModel):
    pass


class UpdateMapRunOutput(BaseModel):
    pass


class MissingRequiredParameter(BaseModel):
    __root__: Any


class ActivityFailedEventDetails(BaseModel):
    error: SecretStr | None = None
    cause: SecretStr | None = None


class ActivityScheduleFailedEventDetails(BaseModel):
    error: SecretStr | None = None
    cause: SecretStr | None = None


class ActivityStartedEventDetails(BaseModel):
    workerName: constr(max_length=256) | None = None


class ActivityTimedOutEventDetails(BaseModel):
    error: SecretStr | None = None
    cause: SecretStr | None = None


class BillingDetails(BaseModel):
    billedMemoryUsedInMB: conint(ge=0) | None = None
    billedDurationInMilliseconds: conint(ge=0) | None = None


class CloudWatchEventsExecutionDataDetails(BaseModel):
    included: bool | None = None


class CloudWatchLogsLogGroup(BaseModel):
    logGroupArn: constr(min_length=1, max_length=256) | None = None


class StateMachineType(Enum):
    STANDARD = "STANDARD"
    EXPRESS = "EXPRESS"


class ExecutionStatus(Enum):
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    TIMED_OUT = "TIMED_OUT"
    ABORTED = "ABORTED"


class MapRunStatus(Enum):
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    ABORTED = "ABORTED"


class StateMachineStatus(Enum):
    ACTIVE = "ACTIVE"
    DELETING = "DELETING"


class ExecutionAbortedEventDetails(BaseModel):
    error: SecretStr | None = None
    cause: SecretStr | None = None


class ExecutionFailedEventDetails(BaseModel):
    error: SecretStr | None = None
    cause: SecretStr | None = None


class ExecutionTimedOutEventDetails(BaseModel):
    error: SecretStr | None = None
    cause: SecretStr | None = None


class HistoryEventType(Enum):
    ActivityFailed = "ActivityFailed"
    ActivityScheduled = "ActivityScheduled"
    ActivityScheduleFailed = "ActivityScheduleFailed"
    ActivityStarted = "ActivityStarted"
    ActivitySucceeded = "ActivitySucceeded"
    ActivityTimedOut = "ActivityTimedOut"
    ChoiceStateEntered = "ChoiceStateEntered"
    ChoiceStateExited = "ChoiceStateExited"
    ExecutionAborted = "ExecutionAborted"
    ExecutionFailed = "ExecutionFailed"
    ExecutionStarted = "ExecutionStarted"
    ExecutionSucceeded = "ExecutionSucceeded"
    ExecutionTimedOut = "ExecutionTimedOut"
    FailStateEntered = "FailStateEntered"
    LambdaFunctionFailed = "LambdaFunctionFailed"
    LambdaFunctionScheduled = "LambdaFunctionScheduled"
    LambdaFunctionScheduleFailed = "LambdaFunctionScheduleFailed"
    LambdaFunctionStarted = "LambdaFunctionStarted"
    LambdaFunctionStartFailed = "LambdaFunctionStartFailed"
    LambdaFunctionSucceeded = "LambdaFunctionSucceeded"
    LambdaFunctionTimedOut = "LambdaFunctionTimedOut"
    MapIterationAborted = "MapIterationAborted"
    MapIterationFailed = "MapIterationFailed"
    MapIterationStarted = "MapIterationStarted"
    MapIterationSucceeded = "MapIterationSucceeded"
    MapStateAborted = "MapStateAborted"
    MapStateEntered = "MapStateEntered"
    MapStateExited = "MapStateExited"
    MapStateFailed = "MapStateFailed"
    MapStateStarted = "MapStateStarted"
    MapStateSucceeded = "MapStateSucceeded"
    ParallelStateAborted = "ParallelStateAborted"
    ParallelStateEntered = "ParallelStateEntered"
    ParallelStateExited = "ParallelStateExited"
    ParallelStateFailed = "ParallelStateFailed"
    ParallelStateStarted = "ParallelStateStarted"
    ParallelStateSucceeded = "ParallelStateSucceeded"
    PassStateEntered = "PassStateEntered"
    PassStateExited = "PassStateExited"
    SucceedStateEntered = "SucceedStateEntered"
    SucceedStateExited = "SucceedStateExited"
    TaskFailed = "TaskFailed"
    TaskScheduled = "TaskScheduled"
    TaskStarted = "TaskStarted"
    TaskStartFailed = "TaskStartFailed"
    TaskStateAborted = "TaskStateAborted"
    TaskStateEntered = "TaskStateEntered"
    TaskStateExited = "TaskStateExited"
    TaskSubmitFailed = "TaskSubmitFailed"
    TaskSubmitted = "TaskSubmitted"
    TaskSucceeded = "TaskSucceeded"
    TaskTimedOut = "TaskTimedOut"
    WaitStateAborted = "WaitStateAborted"
    WaitStateEntered = "WaitStateEntered"
    WaitStateExited = "WaitStateExited"
    MapRunAborted = "MapRunAborted"
    MapRunFailed = "MapRunFailed"
    MapRunStarted = "MapRunStarted"
    MapRunSucceeded = "MapRunSucceeded"


class TaskFailedEventDetails(BaseModel):
    resourceType: constr(min_length=1, max_length=80)
    resource: constr(min_length=1, max_length=80)
    error: SecretStr | None = None
    cause: SecretStr | None = None


class TaskStartFailedEventDetails(BaseModel):
    resourceType: constr(min_length=1, max_length=80)
    resource: constr(min_length=1, max_length=80)
    error: SecretStr | None = None
    cause: SecretStr | None = None


class TaskStartedEventDetails(BaseModel):
    resourceType: constr(min_length=1, max_length=80)
    resource: constr(min_length=1, max_length=80)


class TaskSubmitFailedEventDetails(BaseModel):
    resourceType: constr(min_length=1, max_length=80)
    resource: constr(min_length=1, max_length=80)
    error: SecretStr | None = None
    cause: SecretStr | None = None


class TaskTimedOutEventDetails(BaseModel):
    resourceType: constr(min_length=1, max_length=80)
    resource: constr(min_length=1, max_length=80)
    error: SecretStr | None = None
    cause: SecretStr | None = None


class MapStateStartedEventDetails(BaseModel):
    length: conint(ge=0) | None = None


class MapIterationEventDetails(BaseModel):
    name: constr(min_length=1, max_length=80) | None = None
    index: conint(ge=0) | None = None


class LambdaFunctionFailedEventDetails(BaseModel):
    error: SecretStr | None = None
    cause: SecretStr | None = None


class LambdaFunctionScheduleFailedEventDetails(BaseModel):
    error: SecretStr | None = None
    cause: SecretStr | None = None


class LambdaFunctionStartFailedEventDetails(BaseModel):
    error: SecretStr | None = None
    cause: SecretStr | None = None


class LambdaFunctionTimedOutEventDetails(BaseModel):
    error: SecretStr | None = None
    cause: SecretStr | None = None


class MapRunStartedEventDetails(BaseModel):
    mapRunArn: constr(min_length=1, max_length=2000) | None = None


class MapRunFailedEventDetails(BaseModel):
    error: SecretStr | None = None
    cause: SecretStr | None = None


class TaskCredentials(BaseModel):
    roleArn: constr(min_length=1, max_length=2000) | None = None


class LogDestination(BaseModel):
    cloudWatchLogsLogGroup: CloudWatchLogsLogGroup | None = None


class LogLevel(Enum):
    ALL = "ALL"
    ERROR = "ERROR"
    FATAL = "FATAL"
    OFF = "OFF"


class MapRunListItem(BaseModel):
    executionArn: constr(min_length=1, max_length=256)
    mapRunArn: constr(min_length=1, max_length=2000)
    stateMachineArn: constr(min_length=1, max_length=256)
    startDate: datetime
    stopDate: datetime | None = None


class SyncExecutionStatus(Enum):
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    TIMED_OUT = "TIMED_OUT"


class StateMachineListItem(BaseModel):
    stateMachineArn: constr(min_length=1, max_length=256)
    name: constr(min_length=1, max_length=80)
    type: StateMachineType
    creationDate: datetime


class Tag(BaseModel):
    key: constr(min_length=1, max_length=128) | None = None
    value: constr(min_length=0, max_length=256) | None = None


class CreateActivityOutput(BaseModel):
    activityArn: constr(min_length=1, max_length=256)
    creationDate: datetime


class CreateStateMachineOutput(BaseModel):
    stateMachineArn: constr(min_length=1, max_length=256)
    creationDate: datetime


class DeleteActivityInput(BaseModel):
    activityArn: constr(min_length=1, max_length=256)


class DeleteStateMachineInput(BaseModel):
    stateMachineArn: constr(min_length=1, max_length=256)


class DescribeActivityOutput(BaseModel):
    activityArn: constr(min_length=1, max_length=256)
    name: constr(min_length=1, max_length=80)
    creationDate: datetime


class DescribeActivityInput(BaseModel):
    activityArn: constr(min_length=1, max_length=256)


class DescribeExecutionOutput(BaseModel):
    executionArn: constr(min_length=1, max_length=256)
    stateMachineArn: constr(min_length=1, max_length=256)
    name: constr(min_length=1, max_length=80) | None = None
    status: ExecutionStatus
    startDate: datetime
    stopDate: datetime | None = None
    input: SecretStr | None = None
    inputDetails: CloudWatchEventsExecutionDataDetails | None = None
    output: SecretStr | None = None
    outputDetails: CloudWatchEventsExecutionDataDetails | None = None
    traceHeader: None | (
        constr(regex=r"[\x00-\x7F]*", min_length=0, max_length=256)
    ) = None
    mapRunArn: constr(min_length=1, max_length=2000) | None = None
    error: SecretStr | None = None
    cause: SecretStr | None = None


class DescribeExecutionInput(BaseModel):
    executionArn: constr(min_length=1, max_length=256)


class DescribeMapRunInput(BaseModel):
    mapRunArn: constr(min_length=1, max_length=2000)


class DescribeStateMachineInput(BaseModel):
    stateMachineArn: constr(min_length=1, max_length=256)


class DescribeStateMachineForExecutionInput(BaseModel):
    executionArn: constr(min_length=1, max_length=256)


class GetActivityTaskOutput(BaseModel):
    taskToken: constr(min_length=1, max_length=1024) | None = None
    input: SecretStr | None = None


class GetActivityTaskInput(BaseModel):
    activityArn: constr(min_length=1, max_length=256)
    workerName: constr(min_length=1, max_length=80) | None = None


class GetExecutionHistoryInput(BaseModel):
    executionArn: constr(min_length=1, max_length=256)
    maxResults: conint(ge=0, le=1000) | None = None
    reverseOrder: bool | None = None
    nextToken: constr(min_length=1, max_length=1024) | None = None
    includeExecutionData: bool | None = None


class ListActivitiesInput(BaseModel):
    maxResults: conint(ge=0, le=1000) | None = None
    nextToken: constr(min_length=1, max_length=1024) | None = None


class ListExecutionsInput(BaseModel):
    stateMachineArn: constr(min_length=1, max_length=256) | None = None
    statusFilter: ExecutionStatus | None = None
    maxResults: conint(ge=0, le=1000) | None = None
    nextToken: constr(min_length=1, max_length=3096) | None = None
    mapRunArn: constr(min_length=1, max_length=2000) | None = None


class ListMapRunsInput(BaseModel):
    executionArn: constr(min_length=1, max_length=256)
    maxResults: conint(ge=0, le=1000) | None = None
    nextToken: constr(min_length=1, max_length=1024) | None = None


class ListStateMachinesInput(BaseModel):
    maxResults: conint(ge=0, le=1000) | None = None
    nextToken: constr(min_length=1, max_length=1024) | None = None


class ListTagsForResourceInput(BaseModel):
    resourceArn: constr(min_length=1, max_length=256)


class SendTaskFailureInput(BaseModel):
    taskToken: constr(min_length=1, max_length=1024)
    error: SecretStr | None = None
    cause: SecretStr | None = None


class SendTaskHeartbeatInput(BaseModel):
    taskToken: constr(min_length=1, max_length=1024)


class SendTaskSuccessInput(BaseModel):
    taskToken: constr(min_length=1, max_length=1024)
    output: SecretStr


class StartExecutionOutput(BaseModel):
    executionArn: constr(min_length=1, max_length=256)
    startDate: datetime


class StartExecutionInput(BaseModel):
    stateMachineArn: constr(min_length=1, max_length=256)
    name: constr(min_length=1, max_length=80) | None = None
    input: SecretStr | None = None
    traceHeader: None | (
        constr(regex=r"[\x00-\x7F]*", min_length=0, max_length=256)
    ) = None


class StartSyncExecutionOutput(BaseModel):
    executionArn: constr(min_length=1, max_length=256)
    stateMachineArn: constr(min_length=1, max_length=256) | None = None
    name: constr(min_length=1, max_length=80) | None = None
    startDate: datetime
    stopDate: datetime
    status: SyncExecutionStatus
    error: SecretStr | None = None
    cause: SecretStr | None = None
    input: SecretStr | None = None
    inputDetails: CloudWatchEventsExecutionDataDetails | None = None
    output: SecretStr | None = None
    outputDetails: CloudWatchEventsExecutionDataDetails | None = None
    traceHeader: None | (
        constr(regex=r"[\x00-\x7F]*", min_length=0, max_length=256)
    ) = None
    billingDetails: BillingDetails | None = None


class StartSyncExecutionInput(BaseModel):
    stateMachineArn: constr(min_length=1, max_length=256)
    name: constr(min_length=1, max_length=80) | None = None
    input: SecretStr | None = None
    traceHeader: None | (
        constr(regex=r"[\x00-\x7F]*", min_length=0, max_length=256)
    ) = None


class StopExecutionOutput(BaseModel):
    stopDate: datetime


class StopExecutionInput(BaseModel):
    executionArn: constr(min_length=1, max_length=256)
    error: SecretStr | None = None
    cause: SecretStr | None = None


class UntagResourceInput(BaseModel):
    resourceArn: constr(min_length=1, max_length=256)
    tagKeys: list[constr(min_length=1, max_length=128)]


class UpdateMapRunInput(BaseModel):
    mapRunArn: constr(min_length=1, max_length=2000)
    maxConcurrency: conint(ge=0) | None = None
    toleratedFailurePercentage: confloat(ge=0.0, le=100.0) | None = None
    toleratedFailureCount: conint(ge=0) | None = None


class UpdateStateMachineOutput(BaseModel):
    updateDate: datetime


class ActivityListItem(BaseModel):
    activityArn: constr(min_length=1, max_length=256)
    name: constr(min_length=1, max_length=80)
    creationDate: datetime


class HistoryEventExecutionDataDetails(BaseModel):
    truncated: bool | None = None


class ActivityScheduledEventDetails(BaseModel):
    resource: constr(min_length=1, max_length=256)
    input: SecretStr | None = None
    inputDetails: HistoryEventExecutionDataDetails | None = None
    timeoutInSeconds: int | None = None
    heartbeatInSeconds: int | None = None


class ActivitySucceededEventDetails(BaseModel):
    output: SecretStr | None = None
    outputDetails: HistoryEventExecutionDataDetails | None = None


class LoggingConfiguration(BaseModel):
    level: LogLevel | None = None
    includeExecutionData: bool | None = None
    destinations: list[LogDestination] | None = None


class TracingConfiguration(BaseModel):
    enabled: bool | None = None


class MapRunItemCounts(BaseModel):
    pending: conint(ge=0)
    running: conint(ge=0)
    succeeded: conint(ge=0)
    failed: conint(ge=0)
    timedOut: conint(ge=0)
    aborted: conint(ge=0)
    total: conint(ge=0)
    resultsWritten: conint(ge=0)


class MapRunExecutionCounts(BaseModel):
    pending: conint(ge=0)
    running: conint(ge=0)
    succeeded: conint(ge=0)
    failed: conint(ge=0)
    timedOut: conint(ge=0)
    aborted: conint(ge=0)
    total: conint(ge=0)
    resultsWritten: conint(ge=0)


class ExecutionListItem(BaseModel):
    executionArn: constr(min_length=1, max_length=256)
    stateMachineArn: constr(min_length=1, max_length=256)
    name: constr(min_length=1, max_length=80)
    status: ExecutionStatus
    startDate: datetime
    stopDate: datetime | None = None
    mapRunArn: constr(min_length=1, max_length=2000) | None = None
    itemCount: conint(ge=0) | None = None


class ExecutionStartedEventDetails(BaseModel):
    input: SecretStr | None = None
    inputDetails: HistoryEventExecutionDataDetails | None = None
    roleArn: constr(min_length=1, max_length=256) | None = None


class ExecutionSucceededEventDetails(BaseModel):
    output: SecretStr | None = None
    outputDetails: HistoryEventExecutionDataDetails | None = None


class TaskScheduledEventDetails(BaseModel):
    resourceType: constr(min_length=1, max_length=80)
    resource: constr(min_length=1, max_length=80)
    region: constr(min_length=1, max_length=80)
    parameters: SecretStr
    timeoutInSeconds: int | None = None
    heartbeatInSeconds: int | None = None
    taskCredentials: TaskCredentials | None = None


class TaskSubmittedEventDetails(BaseModel):
    resourceType: constr(min_length=1, max_length=80)
    resource: constr(min_length=1, max_length=80)
    output: SecretStr | None = None
    outputDetails: HistoryEventExecutionDataDetails | None = None


class TaskSucceededEventDetails(BaseModel):
    resourceType: constr(min_length=1, max_length=80)
    resource: constr(min_length=1, max_length=80)
    output: SecretStr | None = None
    outputDetails: HistoryEventExecutionDataDetails | None = None


class LambdaFunctionScheduledEventDetails(BaseModel):
    resource: constr(min_length=1, max_length=256)
    input: SecretStr | None = None
    inputDetails: HistoryEventExecutionDataDetails | None = None
    timeoutInSeconds: int | None = None
    taskCredentials: TaskCredentials | None = None


class LambdaFunctionSucceededEventDetails(BaseModel):
    output: SecretStr | None = None
    outputDetails: HistoryEventExecutionDataDetails | None = None


class StateEnteredEventDetails(BaseModel):
    name: constr(min_length=1, max_length=80)
    input: SecretStr | None = None
    inputDetails: HistoryEventExecutionDataDetails | None = None


class StateExitedEventDetails(BaseModel):
    name: constr(min_length=1, max_length=80)
    output: SecretStr | None = None
    outputDetails: HistoryEventExecutionDataDetails | None = None


class HistoryEvent(BaseModel):
    timestamp: datetime
    type: HistoryEventType
    id: int
    previousEventId: int | None = None
    activityFailedEventDetails: ActivityFailedEventDetails | None = None
    activityScheduleFailedEventDetails: None | (
        ActivityScheduleFailedEventDetails
    ) = None
    activityScheduledEventDetails: ActivityScheduledEventDetails | None = None
    activityStartedEventDetails: ActivityStartedEventDetails | None = None
    activitySucceededEventDetails: ActivitySucceededEventDetails | None = None
    activityTimedOutEventDetails: ActivityTimedOutEventDetails | None = None
    taskFailedEventDetails: TaskFailedEventDetails | None = None
    taskScheduledEventDetails: TaskScheduledEventDetails | None = None
    taskStartFailedEventDetails: TaskStartFailedEventDetails | None = None
    taskStartedEventDetails: TaskStartedEventDetails | None = None
    taskSubmitFailedEventDetails: TaskSubmitFailedEventDetails | None = None
    taskSubmittedEventDetails: TaskSubmittedEventDetails | None = None
    taskSucceededEventDetails: TaskSucceededEventDetails | None = None
    taskTimedOutEventDetails: TaskTimedOutEventDetails | None = None
    executionFailedEventDetails: ExecutionFailedEventDetails | None = None
    executionStartedEventDetails: ExecutionStartedEventDetails | None = None
    executionSucceededEventDetails: ExecutionSucceededEventDetails | None = None
    executionAbortedEventDetails: ExecutionAbortedEventDetails | None = None
    executionTimedOutEventDetails: ExecutionTimedOutEventDetails | None = None
    mapStateStartedEventDetails: MapStateStartedEventDetails | None = None
    mapIterationStartedEventDetails: MapIterationEventDetails | None = None
    mapIterationSucceededEventDetails: MapIterationEventDetails | None = None
    mapIterationFailedEventDetails: MapIterationEventDetails | None = None
    mapIterationAbortedEventDetails: MapIterationEventDetails | None = None
    lambdaFunctionFailedEventDetails: LambdaFunctionFailedEventDetails | None = None
    lambdaFunctionScheduleFailedEventDetails: None | (
        LambdaFunctionScheduleFailedEventDetails
    ) = None
    lambdaFunctionScheduledEventDetails: None | (
        LambdaFunctionScheduledEventDetails
    ) = None
    lambdaFunctionStartFailedEventDetails: None | (
        LambdaFunctionStartFailedEventDetails
    ) = None
    lambdaFunctionSucceededEventDetails: None | (
        LambdaFunctionSucceededEventDetails
    ) = None
    lambdaFunctionTimedOutEventDetails: None | (
        LambdaFunctionTimedOutEventDetails
    ) = None
    stateEnteredEventDetails: StateEnteredEventDetails | None = None
    stateExitedEventDetails: StateExitedEventDetails | None = None
    mapRunStartedEventDetails: MapRunStartedEventDetails | None = None
    mapRunFailedEventDetails: MapRunFailedEventDetails | None = None


class CreateActivityInput(BaseModel):
    name: constr(min_length=1, max_length=80)
    tags: list[Tag] | None = None


class CreateStateMachineInput(BaseModel):
    name: constr(min_length=1, max_length=80)
    definition: SecretStr
    roleArn: constr(min_length=1, max_length=256)
    type: StateMachineType | None = None
    loggingConfiguration: LoggingConfiguration | None = None
    tags: list[Tag] | None = None
    tracingConfiguration: TracingConfiguration | None = None


class DescribeMapRunOutput(BaseModel):
    mapRunArn: constr(min_length=1, max_length=2000)
    executionArn: constr(min_length=1, max_length=256)
    status: MapRunStatus
    startDate: datetime
    stopDate: datetime | None = None
    maxConcurrency: conint(ge=0)
    toleratedFailurePercentage: confloat(ge=0.0, le=100.0)
    toleratedFailureCount: conint(ge=0)
    itemCounts: MapRunItemCounts
    executionCounts: MapRunExecutionCounts


class DescribeStateMachineOutput(BaseModel):
    stateMachineArn: constr(min_length=1, max_length=256)
    name: constr(min_length=1, max_length=80)
    status: StateMachineStatus | None = None
    definition: SecretStr
    roleArn: constr(min_length=1, max_length=256)
    type: StateMachineType
    creationDate: datetime
    loggingConfiguration: LoggingConfiguration | None = None
    tracingConfiguration: TracingConfiguration | None = None
    label: str | None = None


class DescribeStateMachineForExecutionOutput(BaseModel):
    stateMachineArn: constr(min_length=1, max_length=256)
    name: constr(min_length=1, max_length=80)
    definition: SecretStr
    roleArn: constr(min_length=1, max_length=256)
    updateDate: datetime
    loggingConfiguration: LoggingConfiguration | None = None
    tracingConfiguration: TracingConfiguration | None = None
    mapRunArn: constr(min_length=1, max_length=2000) | None = None
    label: str | None = None


class ListActivitiesOutput(BaseModel):
    activities: list[ActivityListItem]
    nextToken: constr(min_length=1, max_length=1024) | None = None


class ListExecutionsOutput(BaseModel):
    executions: list[ExecutionListItem]
    nextToken: constr(min_length=1, max_length=3096) | None = None


class ListMapRunsOutput(BaseModel):
    mapRuns: list[MapRunListItem]
    nextToken: constr(min_length=1, max_length=1024) | None = None


class ListStateMachinesOutput(BaseModel):
    stateMachines: list[StateMachineListItem]
    nextToken: constr(min_length=1, max_length=1024) | None = None


class ListTagsForResourceOutput(BaseModel):
    tags: list[Tag] | None = None


class TagResourceInput(BaseModel):
    resourceArn: constr(min_length=1, max_length=256)
    tags: list[Tag]


class UpdateStateMachineInput(BaseModel):
    stateMachineArn: constr(min_length=1, max_length=256)
    definition: SecretStr | None = None
    roleArn: constr(min_length=1, max_length=256) | None = None
    loggingConfiguration: LoggingConfiguration | None = None
    tracingConfiguration: TracingConfiguration | None = None


class GetExecutionHistoryOutput(BaseModel):
    events: list[HistoryEvent] = Field(
        ...,
        description="Contains details about the events that occurred during an execution.",
    )
    nextToken: constr(min_length=1, max_length=1024) | None = None
